### ISSUE TITLE
CircleCI build artifact is invisible to non-maintainers

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/vpnkit#431]
CircleCI build artifact is invisible to non-maintainers, but I'm not sure how to fix the issue. 

Maybe the best ways is to ship regular binary release for non-maintainers.

(I want Linux binary artifact as well, because [RootlessKit](https://github.com/rootless-containers/rootlesskit) CI spends most time in building VPNKit for integration testing)

**Comment by djs55** [comment]
A regular binary release sounds like a good idea.

Making portable Linux binaries from OCaml programs is a little tricky, as the OCaml runtime links against the system libc (unlike Go). Maybe a static link would work. Otherwise we'll have to choose which environment(s) to build it in and publish multiple binaries.

**Comment by AkihiroSuda** [comment]
Yes, static link (with musl) is possible
 https://github.com/moby/vpnkit/issues/407#issuecomment-404777050

**Comment by djs55** [comment]
For Linux the `Dockerfile` now builds a static binary (with musl) and there's a hub auto-builder which creates this image:
```
docker run djs55/vpnkit:latest /vpnkit --help
```

**Comment by AkihiroSuda** [comment]
Thanks!
